#!/usr/bin/env python3
"""Build a Pico 2 W (RP2350) firmware with the Nova D1 package FROZEN into flash.

Why this exists
---------------
Measured on hardware: the Nova D1 package costs ~187 KB of a 447 KB heap, because
every .mpy is loaded into RAM. Frozen modules live in FLASH and are executed in
place, so freezing the package moves that cost off the heap entirely. No amount
of lazy-importing gets close to that — it is the difference between shaving the
problem and removing it.

No fork
-------
This does NOT copy or modify a single line of the package. It generates a
manifest that points the freezer at the .py files in RPCortex-repo where they
already live, so the ESP32-S3 keeps loading exactly the same sources from its
filesystem and there is only ever one copy of the code.

Updating a frozen build
-----------------------
sys.path is ['', '.frozen', '/lib'], and RPCortex inserts an installed package's
directory at index 1 — ahead of '.frozen'. So a frozen module is the BASELINE and
an installed update overrides it:

  * fresh flash        -> nothing in /Packages, frozen copies run, minimum RAM
  * after pkg upgrade  -> the installed files win, normal RAM, newest code
  * next .uf2          -> folds the update back into flash, RAM cost gone again

That is why the loader inserts rather than appends; appending would leave the
frozen copy winning and an update would silently do nothing.

Usage
-----
    python3 RPCortex-OS/tools/build_rp2350.py            # build
    python3 RPCortex-OS/tools/build_rp2350.py --clean    # from scratch
    python3 RPCortex-OS/tools/build_rp2350.py --list     # what would be frozen

First time only, to fetch the toolchain sources (~1 GB):

    git clone https://github.com/micropython/micropython firmware/mp
    cd firmware/mp && git checkout <the commit the device runs>
    make -C ports/rp2 BOARD=RPI_PICO2_W submodules
"""
import argparse
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
# .../RPC-Workspace/RPCortex-OS/tools -> the workspace root, which is where the
# sibling repos and the firmware tree live.
ROOT = os.path.dirname(os.path.dirname(HERE))
MP = os.path.join(ROOT, 'firmware', 'mp')
PORT = os.path.join(MP, 'ports', 'rp2')
BOARD = 'RPI_PICO2_W'
PKG = os.path.join(ROOT, 'RPCortex-repo', 'repo', 'packages', 'novad1')
OUT = os.path.join(ROOT, 'firmware', 'out')

# Everything in the package is frozen except this. novafont is the old 8x8 font,
# superseded by novafont5x7 — novasplash was its last caller and no longer is.
#
# novad1 (the CLI) IS frozen despite loading on demand: on-demand still means
# ~44 KB of heap the moment you type `d1`, and frozen costs nothing either way.
SKIP = {'novafont'}


def modules():
    """Every Nova D1 module to freeze, as (module_name, absolute path)."""
    out = []
    for fn in sorted(os.listdir(PKG)):
        if not fn.endswith('.py'):
            continue
        name = fn[:-3]
        if name in SKIP:
            continue
        out.append((name, os.path.join(PKG, fn)))
    return out


MANIFEST_HEADER = '''# GENERATED by tools/build_rp2350.py — do not edit, do not commit.
#
# Freezes the Nova D1 package into the firmware image. The paths point at the
# package sources in RPCortex-repo; nothing is copied, so this cannot drift from
# what the ESP32-S3 loads off its filesystem.

include("$(PORT_DIR)/boards/manifest.py")

'''


def write_manifest(path):
    lines = [MANIFEST_HEADER]
    for _name, src in modules():
        lines.append('freeze_as_mpy("%s", "%s")' % (
            os.path.dirname(src), os.path.basename(src)))
    open(path, 'w').write('\n'.join(lines) + '\n')


def run(cmd, **kw):
    print('$', ' '.join(cmd))
    return subprocess.call(cmd, **kw)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--clean', action='store_true')
    ap.add_argument('--list', action='store_true')
    ap.add_argument('--board', default=BOARD)
    a = ap.parse_args()

    mods = modules()
    if a.list:
        total = sum(os.path.getsize(p) for _n, p in mods)
        for n, p in mods:
            print('  %-18s %6d B' % (n, os.path.getsize(p)))
        print('  %d modules, %d B of source' % (len(mods), total))
        return 0

    if not os.path.isdir(MP):
        print('MicroPython tree not found at', MP)
        print('Clone it:  git clone https://github.com/micropython/micropython '
              + MP)
        return 1

    manifest = os.path.join(ROOT, 'firmware', 'novad1_manifest.py')
    write_manifest(manifest)
    print('manifest:', manifest, '(%d modules)' % len(mods))

    build = os.path.join(PORT, 'build-%s' % a.board)
    if a.clean and os.path.isdir(build):
        run(['rm', '-rf', build])

    rc = run(['make', '-C', PORT, 'BOARD=%s' % a.board,
              'FROZEN_MANIFEST=%s' % manifest,
              '-j%d' % (os.cpu_count() or 4)])
    if rc:
        print('BUILD FAILED')
        return rc

    os.makedirs(OUT, exist_ok=True)
    uf2 = os.path.join(build, 'firmware.uf2')
    if not os.path.exists(uf2):
        print('no firmware.uf2 produced')
        return 1
    dest = os.path.join(OUT, 'RPC-NovaD1-%s.uf2' % a.board.lower())
    run(['cp', uf2, dest])
    print('\n  ->', dest, '(%d bytes)' % os.path.getsize(dest))
    print('\n  Flash: hold BOOTSEL, plug in, copy that .uf2 to the RPI-RP2 drive.')
    print('  It REPLACES MicroPython. The filesystem region is untouched, but')
    print('  treat a reflash as destructive and be ready to reinstall RPCortex.')
    return 0


if __name__ == '__main__':
    sys.exit(main())
